# Generated by Django 4.0.6 on 2022-09-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media', verbose_name='Foto del jugador')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre del jugador')),
                ('Dia_de_nacimiento', models.DateField(verbose_name='Dia de nacimiento')),
                ('Edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('Numero', models.PositiveIntegerField(verbose_name='Numero de camiseta')),
                ('titular', models.BooleanField(default=True, verbose_name='Titular')),
                ('Posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.posicion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugador',
                'ordering': ['id'],
            },
        ),
    ]
