# Generated by Django 4.0.6 on 2022-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='Edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
