# Generated by Django 4.0.6 on 2022-09-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0003_alter_jugador_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Rol')),
                ('Image', models.ImageField(upload_to='media', verbose_name='Imagen del pais')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'Nacionalidad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='media', verbose_name='Foto del tecnico')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre del tecnico')),
                ('Dia_de_nacimiento', models.DateField(verbose_name='Dia de nacimiento')),
                ('Edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('Nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.nacionalidad')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.rol')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipo')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': '',
                'ordering': ['id'],
            },
        ),
    ]
