# Generated by Django 4.0.6 on 2022-09-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0005_alter_nacionalidad_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nacionalidad',
            name='Image',
        ),
    ]
